#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : apache-tomcat
Version  : 9.0.20
Release  : 4
URL      : https://github.com/apache/tomcat/archive/9.0.20.tar.gz
Source0  : https://github.com/apache/tomcat/archive/9.0.20.tar.gz
Source1  : https://archive.apache.org/dist/commons/daemon/source/commons-daemon-1.1.0-native-src.tar.gz
Source2  : https://archive.apache.org/dist/tomcat/tomcat-connectors/native/1.2.21/source/tomcat-native-1.2.21-src.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 CDDL-1.0 EPL-1.0
Requires: apache-tomcat-bin = %{version}-%{release}
Requires: apache-tomcat-data = %{version}-%{release}
Requires: openjdk
BuildRequires : apache-ant
BuildRequires : buildreq-mvn
BuildRequires : mvn-biz.aQute.bnd
BuildRequires : mvn-biz.aQute.bndlib
BuildRequires : mvn-commons-daemon
BuildRequires : mvn-ecj
BuildRequires : mvn-geronimo-spec-jaxrpc
BuildRequires : mvn-saaj-api
BuildRequires : mvn-wsdl4j
BuildRequires : openjdk
BuildRequires : openjdk-dev
Patch1: 0002-remove-windows-zip-downloading-and-javadoc-build-in-.patch
Patch2: 0003-Stateless.patch

%description
## Welcome to Apache Tomcat!
### What Is It?
The Apache Tomcat® software is an open source implementation of the Java
Servlet, JavaServer Pages, Java Expression Language and Java WebSocket
technologies. The Java Servlet, JavaServer Pages, Java Expression Language and
Java WebSocket specifications are developed under the
[Java Community Process](https://jcp.org/en/introduction/overview).

%package bin
Summary: bin components for the apache-tomcat package.
Group: Binaries
Requires: apache-tomcat-data = %{version}-%{release}

%description bin
bin components for the apache-tomcat package.


%package data
Summary: data components for the apache-tomcat package.
Group: Data

%description data
data components for the apache-tomcat package.


%package doc
Summary: doc components for the apache-tomcat package.
Group: Documentation

%description doc
doc components for the apache-tomcat package.


%prep
%setup -q -n tomcat-9.0.20
cd ..
%setup -q -T -D -n tomcat-9.0.20 -b 2
cd ..
%setup -q -T -D -n tomcat-9.0.20 -b 1
%patch1 -p1
%patch2 -p1

%build
## build_prepend content
mkdir -p tomcat-build-libs/commons-daemon-1.1.0
cp %{SOURCE1} tomcat-build-libs/commons-daemon-1.1.0/
mkdir -p tomcat-build-libs/tomcat-native-1.2.21
cp %{SOURCE2} tomcat-build-libs/tomcat-native-1.2.21/tomcat-native.tar.gz
## build_prepend end
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export ANT_HOME=/usr/share/ant
ant release -Dskip.installer=true \
-Dbase.path=./tomcat-build-libs \
-Dcommons-daemon.jar=/usr/share/java/.m2/repository/commons-daemon/commons-daemon/1.1.0/commons-daemon-1.1.0.jar \
-Djdt.jar=/usr/share/java/.m2/repository/org/eclipse/jdt/core/compiler/ecj/ecj-4.10.jar \
-Dbndlib.jar=/usr/share/java/.m2/repository/biz/aQute/bnd/biz.aQute.bndlib/4.0.0/biz.aQute.bndlib-4.0.0.jar \
-Dsaaj-api.jar=/usr/share/java/.m2/repository/javax/xml/soap/saaj-api/1.3.5/saaj-api-1.3.5.jar \
-Djaxrpc-lib.jar=/usr/share/java/.m2/repository/geronimo-spec/geronimo-spec-jaxrpc/1.1-rc4/geronimo-spec-jaxrpc-1.1-rc4.jar \
-Dwsdl4j-lib.jar=/usr/share/java/.m2/repository/wsdl4j/wsdl4j/1.6.3/wsdl4j-1.6.3.jar \
-Dbnd.jar=/usr/share/java/.m2/repository/biz/aQute/bnd/biz.aQute.bnd/4.0.0/biz.aQute.bnd-4.0.0.jar
%install

## install_append content
mkdir -p %{buildroot}/usr/share/doc/apache-tomcat
tar -xf output/release/v9.0.20/bin/apache-tomcat-9.0.20-fulldocs.tar.gz -C %{buildroot}/usr/share/doc/apache-tomcat --strip-components=1
mkdir -p %{buildroot}/usr/share/apache-tomcat
tar -xf output/release/v9.0.20/bin/apache-tomcat-9.0.20.tar.gz -C %{buildroot}/usr/share/apache-tomcat/ --strip-components=1
mkdir -p %{buildroot}/usr/bin
cd %{buildroot}/usr/bin
find ../share/apache-tomcat/bin -type f -name *.sh -exec ln -s {} . \;
cd -
install -d -m 750 %{buildroot}/usr/share/defaults/tomcat/conf/
install -p -D -m 600 %{buildroot}/usr/share/apache-tomcat/conf/* %{buildroot}/usr/share/defaults/tomcat/conf/
## install_append end

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/catalina.sh
/usr/bin/ciphers.sh
/usr/bin/configtest.sh
/usr/bin/daemon.sh
/usr/bin/digest.sh
/usr/bin/makebase.sh
/usr/bin/setclasspath.sh
/usr/bin/shutdown.sh
/usr/bin/startup.sh
/usr/bin/tool-wrapper.sh
/usr/bin/version.sh

%files data
%defattr(-,root,root,-)
/usr/share/apache-tomcat/BUILDING.txt
/usr/share/apache-tomcat/CONTRIBUTING.md
/usr/share/apache-tomcat/LICENSE
/usr/share/apache-tomcat/NOTICE
/usr/share/apache-tomcat/README.md
/usr/share/apache-tomcat/RELEASE-NOTES
/usr/share/apache-tomcat/RUNNING.txt
/usr/share/apache-tomcat/bin/bootstrap.jar
/usr/share/apache-tomcat/bin/catalina-tasks.xml
/usr/share/apache-tomcat/bin/catalina.bat
/usr/share/apache-tomcat/bin/catalina.sh
/usr/share/apache-tomcat/bin/ciphers.bat
/usr/share/apache-tomcat/bin/ciphers.sh
/usr/share/apache-tomcat/bin/commons-daemon-native.tar.gz
/usr/share/apache-tomcat/bin/commons-daemon.jar
/usr/share/apache-tomcat/bin/configtest.bat
/usr/share/apache-tomcat/bin/configtest.sh
/usr/share/apache-tomcat/bin/daemon.sh
/usr/share/apache-tomcat/bin/digest.bat
/usr/share/apache-tomcat/bin/digest.sh
/usr/share/apache-tomcat/bin/makebase.bat
/usr/share/apache-tomcat/bin/makebase.sh
/usr/share/apache-tomcat/bin/setclasspath.bat
/usr/share/apache-tomcat/bin/setclasspath.sh
/usr/share/apache-tomcat/bin/shutdown.bat
/usr/share/apache-tomcat/bin/shutdown.sh
/usr/share/apache-tomcat/bin/startup.bat
/usr/share/apache-tomcat/bin/startup.sh
/usr/share/apache-tomcat/bin/tomcat-juli.jar
/usr/share/apache-tomcat/bin/tomcat-native.tar.gz
/usr/share/apache-tomcat/bin/tool-wrapper.bat
/usr/share/apache-tomcat/bin/tool-wrapper.sh
/usr/share/apache-tomcat/bin/version.bat
/usr/share/apache-tomcat/bin/version.sh
/usr/share/apache-tomcat/conf/catalina.policy
/usr/share/apache-tomcat/conf/catalina.properties
/usr/share/apache-tomcat/conf/context.xml
/usr/share/apache-tomcat/conf/jaspic-providers.xml
/usr/share/apache-tomcat/conf/jaspic-providers.xsd
/usr/share/apache-tomcat/conf/logging.properties
/usr/share/apache-tomcat/conf/server.xml
/usr/share/apache-tomcat/conf/tomcat-users.xml
/usr/share/apache-tomcat/conf/tomcat-users.xsd
/usr/share/apache-tomcat/conf/web.xml
/usr/share/apache-tomcat/lib/annotations-api.jar
/usr/share/apache-tomcat/lib/catalina-ant.jar
/usr/share/apache-tomcat/lib/catalina-ha.jar
/usr/share/apache-tomcat/lib/catalina-storeconfig.jar
/usr/share/apache-tomcat/lib/catalina-tribes.jar
/usr/share/apache-tomcat/lib/catalina.jar
/usr/share/apache-tomcat/lib/ecj-4.10.jar
/usr/share/apache-tomcat/lib/el-api.jar
/usr/share/apache-tomcat/lib/jasper-el.jar
/usr/share/apache-tomcat/lib/jasper.jar
/usr/share/apache-tomcat/lib/jaspic-api.jar
/usr/share/apache-tomcat/lib/jsp-api.jar
/usr/share/apache-tomcat/lib/servlet-api.jar
/usr/share/apache-tomcat/lib/tomcat-api.jar
/usr/share/apache-tomcat/lib/tomcat-coyote.jar
/usr/share/apache-tomcat/lib/tomcat-dbcp.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-cs.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-de.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-es.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-fr.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-ja.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-ko.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-pt-BR.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-ru.jar
/usr/share/apache-tomcat/lib/tomcat-i18n-zh-CN.jar
/usr/share/apache-tomcat/lib/tomcat-jdbc.jar
/usr/share/apache-tomcat/lib/tomcat-jni.jar
/usr/share/apache-tomcat/lib/tomcat-util-scan.jar
/usr/share/apache-tomcat/lib/tomcat-util.jar
/usr/share/apache-tomcat/lib/tomcat-websocket.jar
/usr/share/apache-tomcat/lib/websocket-api.jar
/usr/share/apache-tomcat/temp/safeToDelete.tmp
/usr/share/apache-tomcat/webapps/ROOT/RELEASE-NOTES.txt
/usr/share/apache-tomcat/webapps/ROOT/WEB-INF/web.xml
/usr/share/apache-tomcat/webapps/ROOT/asf-logo-wide.svg
/usr/share/apache-tomcat/webapps/ROOT/bg-button.png
/usr/share/apache-tomcat/webapps/ROOT/bg-middle.png
/usr/share/apache-tomcat/webapps/ROOT/bg-nav.png
/usr/share/apache-tomcat/webapps/ROOT/bg-upper.png
/usr/share/apache-tomcat/webapps/ROOT/favicon.ico
/usr/share/apache-tomcat/webapps/ROOT/index.jsp
/usr/share/apache-tomcat/webapps/ROOT/tomcat-power.gif
/usr/share/apache-tomcat/webapps/ROOT/tomcat.css
/usr/share/apache-tomcat/webapps/ROOT/tomcat.gif
/usr/share/apache-tomcat/webapps/ROOT/tomcat.png
/usr/share/apache-tomcat/webapps/ROOT/tomcat.svg
/usr/share/apache-tomcat/webapps/docs/BUILDING.txt
/usr/share/apache-tomcat/webapps/docs/RELEASE-NOTES.txt
/usr/share/apache-tomcat/webapps/docs/RUNNING.txt
/usr/share/apache-tomcat/webapps/docs/WEB-INF/web.xml
/usr/share/apache-tomcat/webapps/docs/aio.html
/usr/share/apache-tomcat/webapps/docs/api/index.html
/usr/share/apache-tomcat/webapps/docs/appdev/build.xml.txt
/usr/share/apache-tomcat/webapps/docs/appdev/deployment.html
/usr/share/apache-tomcat/webapps/docs/appdev/index.html
/usr/share/apache-tomcat/webapps/docs/appdev/installation.html
/usr/share/apache-tomcat/webapps/docs/appdev/introduction.html
/usr/share/apache-tomcat/webapps/docs/appdev/processes.html
/usr/share/apache-tomcat/webapps/docs/appdev/sample/build.xml
/usr/share/apache-tomcat/webapps/docs/appdev/sample/docs/README.txt
/usr/share/apache-tomcat/webapps/docs/appdev/sample/index.html
/usr/share/apache-tomcat/webapps/docs/appdev/sample/sample.war
/usr/share/apache-tomcat/webapps/docs/appdev/sample/src/mypackage/Hello.java
/usr/share/apache-tomcat/webapps/docs/appdev/sample/web/WEB-INF/web.xml
/usr/share/apache-tomcat/webapps/docs/appdev/sample/web/hello.jsp
/usr/share/apache-tomcat/webapps/docs/appdev/sample/web/images/tomcat.gif
/usr/share/apache-tomcat/webapps/docs/appdev/sample/web/index.html
/usr/share/apache-tomcat/webapps/docs/appdev/source.html
/usr/share/apache-tomcat/webapps/docs/appdev/web.xml.txt
/usr/share/apache-tomcat/webapps/docs/apr.html
/usr/share/apache-tomcat/webapps/docs/architecture/index.html
/usr/share/apache-tomcat/webapps/docs/architecture/overview.html
/usr/share/apache-tomcat/webapps/docs/architecture/requestProcess.html
/usr/share/apache-tomcat/webapps/docs/architecture/requestProcess/authentication-process.png
/usr/share/apache-tomcat/webapps/docs/architecture/requestProcess/request-process.png
/usr/share/apache-tomcat/webapps/docs/architecture/startup.html
/usr/share/apache-tomcat/webapps/docs/architecture/startup/serverStartup.pdf
/usr/share/apache-tomcat/webapps/docs/architecture/startup/serverStartup.txt
/usr/share/apache-tomcat/webapps/docs/balancer-howto.html
/usr/share/apache-tomcat/webapps/docs/building.html
/usr/share/apache-tomcat/webapps/docs/cgi-howto.html
/usr/share/apache-tomcat/webapps/docs/changelog.html
/usr/share/apache-tomcat/webapps/docs/class-loader-howto.html
/usr/share/apache-tomcat/webapps/docs/cluster-howto.html
/usr/share/apache-tomcat/webapps/docs/comments.html
/usr/share/apache-tomcat/webapps/docs/config/ajp.html
/usr/share/apache-tomcat/webapps/docs/config/automatic-deployment.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-channel.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-deployer.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-interceptor.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-listener.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-manager.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-membership.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-receiver.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-sender.html
/usr/share/apache-tomcat/webapps/docs/config/cluster-valve.html
/usr/share/apache-tomcat/webapps/docs/config/cluster.html
/usr/share/apache-tomcat/webapps/docs/config/context.html
/usr/share/apache-tomcat/webapps/docs/config/cookie-processor.html
/usr/share/apache-tomcat/webapps/docs/config/credentialhandler.html
/usr/share/apache-tomcat/webapps/docs/config/engine.html
/usr/share/apache-tomcat/webapps/docs/config/executor.html
/usr/share/apache-tomcat/webapps/docs/config/filter.html
/usr/share/apache-tomcat/webapps/docs/config/globalresources.html
/usr/share/apache-tomcat/webapps/docs/config/host.html
/usr/share/apache-tomcat/webapps/docs/config/http.html
/usr/share/apache-tomcat/webapps/docs/config/http2.html
/usr/share/apache-tomcat/webapps/docs/config/index.html
/usr/share/apache-tomcat/webapps/docs/config/jar-scan-filter.html
/usr/share/apache-tomcat/webapps/docs/config/jar-scanner.html
/usr/share/apache-tomcat/webapps/docs/config/jaspic.html
/usr/share/apache-tomcat/webapps/docs/config/listeners.html
/usr/share/apache-tomcat/webapps/docs/config/loader.html
/usr/share/apache-tomcat/webapps/docs/config/manager.html
/usr/share/apache-tomcat/webapps/docs/config/realm.html
/usr/share/apache-tomcat/webapps/docs/config/resources.html
/usr/share/apache-tomcat/webapps/docs/config/server.html
/usr/share/apache-tomcat/webapps/docs/config/service.html
/usr/share/apache-tomcat/webapps/docs/config/sessionidgenerator.html
/usr/share/apache-tomcat/webapps/docs/config/systemprops.html
/usr/share/apache-tomcat/webapps/docs/config/valve.html
/usr/share/apache-tomcat/webapps/docs/connectors.html
/usr/share/apache-tomcat/webapps/docs/default-servlet.html
/usr/share/apache-tomcat/webapps/docs/deployer-howto.html
/usr/share/apache-tomcat/webapps/docs/developers.html
/usr/share/apache-tomcat/webapps/docs/elapi/index.html
/usr/share/apache-tomcat/webapps/docs/extras.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/fs-admin-apps.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/fs-admin-objects.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/fs-admin-opers.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/fs-default.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/fs-jdbc-realm.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/fs-jndi-realm.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/fs-memory-realm.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/index.html
/usr/share/apache-tomcat/webapps/docs/funcspecs/mbean-names.html
/usr/share/apache-tomcat/webapps/docs/host-manager-howto.html
/usr/share/apache-tomcat/webapps/docs/html-host-manager-howto.html
/usr/share/apache-tomcat/webapps/docs/html-manager-howto.html
/usr/share/apache-tomcat/webapps/docs/images/add.gif
/usr/share/apache-tomcat/webapps/docs/images/asf-logo.svg
/usr/share/apache-tomcat/webapps/docs/images/code.gif
/usr/share/apache-tomcat/webapps/docs/images/cors-flowchart.png
/usr/share/apache-tomcat/webapps/docs/images/design.gif
/usr/share/apache-tomcat/webapps/docs/images/docs-stylesheet.css
/usr/share/apache-tomcat/webapps/docs/images/docs.gif
/usr/share/apache-tomcat/webapps/docs/images/fix.gif
/usr/share/apache-tomcat/webapps/docs/images/fonts/OpenSans400.woff
/usr/share/apache-tomcat/webapps/docs/images/fonts/OpenSans400italic.woff
/usr/share/apache-tomcat/webapps/docs/images/fonts/OpenSans600.woff
/usr/share/apache-tomcat/webapps/docs/images/fonts/OpenSans600italic.woff
/usr/share/apache-tomcat/webapps/docs/images/fonts/OpenSans700.woff
/usr/share/apache-tomcat/webapps/docs/images/fonts/OpenSans700italic.woff
/usr/share/apache-tomcat/webapps/docs/images/fonts/fonts.css
/usr/share/apache-tomcat/webapps/docs/images/tomcat.gif
/usr/share/apache-tomcat/webapps/docs/images/tomcat.png
/usr/share/apache-tomcat/webapps/docs/images/update.gif
/usr/share/apache-tomcat/webapps/docs/images/void.gif
/usr/share/apache-tomcat/webapps/docs/index.html
/usr/share/apache-tomcat/webapps/docs/introduction.html
/usr/share/apache-tomcat/webapps/docs/jasper-howto.html
/usr/share/apache-tomcat/webapps/docs/jdbc-pool.html
/usr/share/apache-tomcat/webapps/docs/jndi-datasource-examples-howto.html
/usr/share/apache-tomcat/webapps/docs/jndi-resources-howto.html
/usr/share/apache-tomcat/webapps/docs/jspapi/index.html
/usr/share/apache-tomcat/webapps/docs/logging.html
/usr/share/apache-tomcat/webapps/docs/manager-howto.html
/usr/share/apache-tomcat/webapps/docs/maven-jars.html
/usr/share/apache-tomcat/webapps/docs/mbeans-descriptors-howto.html
/usr/share/apache-tomcat/webapps/docs/mbeans-descriptors.dtd
/usr/share/apache-tomcat/webapps/docs/monitoring.html
/usr/share/apache-tomcat/webapps/docs/proxy-howto.html
/usr/share/apache-tomcat/webapps/docs/realm-howto.html
/usr/share/apache-tomcat/webapps/docs/rewrite.html
/usr/share/apache-tomcat/webapps/docs/security-howto.html
/usr/share/apache-tomcat/webapps/docs/security-manager-howto.html
/usr/share/apache-tomcat/webapps/docs/servletapi/index.html
/usr/share/apache-tomcat/webapps/docs/setup.html
/usr/share/apache-tomcat/webapps/docs/ssi-howto.html
/usr/share/apache-tomcat/webapps/docs/ssl-howto.html
/usr/share/apache-tomcat/webapps/docs/tribes/developers.html
/usr/share/apache-tomcat/webapps/docs/tribes/faq.html
/usr/share/apache-tomcat/webapps/docs/tribes/interceptors.html
/usr/share/apache-tomcat/webapps/docs/tribes/introduction.html
/usr/share/apache-tomcat/webapps/docs/tribes/membership.html
/usr/share/apache-tomcat/webapps/docs/tribes/setup.html
/usr/share/apache-tomcat/webapps/docs/tribes/status.html
/usr/share/apache-tomcat/webapps/docs/tribes/transport.html
/usr/share/apache-tomcat/webapps/docs/virtual-hosting-howto.html
/usr/share/apache-tomcat/webapps/docs/web-socket-howto.html
/usr/share/apache-tomcat/webapps/docs/websocketapi/index.html
/usr/share/apache-tomcat/webapps/docs/windows-auth-howto.html
/usr/share/apache-tomcat/webapps/docs/windows-service-howto.html
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/CookieExample.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/CookieExample.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/HelloWorldExample.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/HelloWorldExample.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_cs.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_de.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_es.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_fr.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_ja.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_ko.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_pt.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_pt_BR.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_ru.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/LocalStrings_zh_CN.properties
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/RequestHeaderExample.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/RequestHeaderExample.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/RequestInfoExample.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/RequestInfoExample.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/RequestParamExample.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/RequestParamExample.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/ServletToJsp.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/ServletToJsp.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/SessionExample.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/SessionExample.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async0$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async0.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async0.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async1$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async1.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async2$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async2.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async2.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async3.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Async3.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/AsyncStockContextListener.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/AsyncStockContextListener.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/AsyncStockServlet.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/AsyncStockServlet.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Stockticker$Stock.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Stockticker$TickListener.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Stockticker.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/async/Stockticker.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/Entries.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/Entries.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/Entry.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/Entry.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/JspCalendar.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/JspCalendar.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/TableBean.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/cal/TableBean.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/checkbox/CheckTest.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/checkbox/CheckTest.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/colors/ColorGameBean.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/colors/ColorGameBean.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilter.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilter.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilterTestServlet.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionFilterTestServlet.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionResponseStream.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionResponseStream.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionServletResponseWrapper.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/compressionFilters/CompressionServletResponseWrapper.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/dates/JspCalendar.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/dates/JspCalendar.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/error/Smart.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/error/Smart.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/ExampleTagBase.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/ExampleTagBase.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/FooTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/FooTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/FooTagExtraInfo.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/FooTagExtraInfo.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/LogTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/LogTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/ValuesTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/examples/ValuesTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/filters/ExampleFilter.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/filters/ExampleFilter.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/http2/SimpleImagePush.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/http2/SimpleImagePush.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/BookBean.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/BookBean.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/FooBean.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/FooBean.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/ValuesBean.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/ValuesBean.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/el/Functions.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/el/Functions.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/EchoAttributesTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/EchoAttributesTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/FindBookSimpleTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/FindBookSimpleTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/HelloWorldSimpleTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/HelloWorldSimpleTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/RepeatSimpleTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/RepeatSimpleTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/ShuffleSimpleTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/ShuffleSimpleTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/TileSimpleTag.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/jsp2/examples/simpletag/TileSimpleTag.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/listeners/ContextListener.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/listeners/ContextListener.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/listeners/SessionListener.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/listeners/SessionListener.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/ByteCounter$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/ByteCounter$CounterListener.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/ByteCounter.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/ByteCounter.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/NumberWriter$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/NumberWriter$NumberWriterListener.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/NumberWriter.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/nonblocking/NumberWriter.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/num/NumberGuessBean.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/num/NumberGuessBean.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/sessions/DummyCart.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/sessions/DummyCart.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/trailers/ResponseTrailers$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/trailers/ResponseTrailers$TrailerFieldSupplier.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/trailers/ResponseTrailers.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/trailers/ResponseTrailers.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/util/CookieFilter.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/util/CookieFilter.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/util/HTMLFilter.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/util/HTMLFilter.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/validators/DebugValidator.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/validators/DebugValidator.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/ExamplesConfig.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/ExamplesConfig.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/chat/ChatAnnotation.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/chat/ChatAnnotation.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Client$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Client.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Client.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawMessage$ParseException.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawMessage.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawMessage.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardContextListener.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardContextListener.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardEndpoint$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardEndpoint$2.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardEndpoint$3$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardEndpoint$3.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardEndpoint.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/DrawboardEndpoint.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Room$1$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Room$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Room$2.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Room$MessageType.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Room$Player.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Room.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/Room.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/AbstractWebsocketMessage.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/AbstractWebsocketMessage.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/BinaryWebsocketMessage.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/BinaryWebsocketMessage.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/CloseWebsocketMessage.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/CloseWebsocketMessage.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/StringWebsocketMessage.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/drawboard/wsmessages/StringWebsocketMessage.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoAnnotation.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoAnnotation.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoAsyncAnnotation$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoAsyncAnnotation$CompletedFuture.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoAsyncAnnotation.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoAsyncAnnotation.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoEndpoint$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoEndpoint$EchoMessageHandlerBinary.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoEndpoint$EchoMessageHandlerText.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoEndpoint.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoEndpoint.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoStreamAnnotation.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/EchoStreamAnnotation.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/echo/servers.json
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/Direction.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/Direction.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/Location$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/Location.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/Location.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/Snake.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/Snake.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/SnakeAnnotation.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/SnakeAnnotation.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/SnakeTimer$1.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/SnakeTimer.class
/usr/share/apache-tomcat/webapps/examples/WEB-INF/classes/websocket/snake/SnakeTimer.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/jsp/applet/Clock2.java
/usr/share/apache-tomcat/webapps/examples/WEB-INF/jsp/debug-taglib.tld
/usr/share/apache-tomcat/webapps/examples/WEB-INF/jsp/example-taglib.tld
/usr/share/apache-tomcat/webapps/examples/WEB-INF/jsp2/jsp2-example-taglib.tld
/usr/share/apache-tomcat/webapps/examples/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar
/usr/share/apache-tomcat/webapps/examples/WEB-INF/lib/taglibs-standard-spec-1.2.5.jar
/usr/share/apache-tomcat/webapps/examples/WEB-INF/tags/displayProducts.tag
/usr/share/apache-tomcat/webapps/examples/WEB-INF/tags/helloWorld.tag
/usr/share/apache-tomcat/webapps/examples/WEB-INF/tags/panel.tag
/usr/share/apache-tomcat/webapps/examples/WEB-INF/web.xml
/usr/share/apache-tomcat/webapps/examples/index.html
/usr/share/apache-tomcat/webapps/examples/jsp/async/async1.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/async/async1.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/async/async3.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/async/async3.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/async/index.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/async/index.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/Entries.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/Entry.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/JspCalendar.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/TableBean.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/cal1.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/cal/cal1.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/cal2.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/cal/cal2.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/calendar.html
/usr/share/apache-tomcat/webapps/examples/jsp/cal/login.html
/usr/share/apache-tomcat/webapps/examples/jsp/checkbox/CheckTest.html
/usr/share/apache-tomcat/webapps/examples/jsp/checkbox/check.html
/usr/share/apache-tomcat/webapps/examples/jsp/checkbox/checkresult.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/checkbox/checkresult.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/checkbox/cresult.html
/usr/share/apache-tomcat/webapps/examples/jsp/colors/ColorGameBean.html
/usr/share/apache-tomcat/webapps/examples/jsp/colors/clr.html
/usr/share/apache-tomcat/webapps/examples/jsp/colors/colors.html
/usr/share/apache-tomcat/webapps/examples/jsp/colors/colrs.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/colors/colrs.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/dates/date.html
/usr/share/apache-tomcat/webapps/examples/jsp/dates/date.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/dates/date.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/error/er.html
/usr/share/apache-tomcat/webapps/examples/jsp/error/err.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/error/err.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/error/error.html
/usr/share/apache-tomcat/webapps/examples/jsp/error/errorpge.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/error/errorpge.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/forward/forward.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/forward/forward.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/forward/fwd.html
/usr/share/apache-tomcat/webapps/examples/jsp/forward/one.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/forward/one.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/forward/two.html
/usr/share/apache-tomcat/webapps/examples/jsp/images/code.gif
/usr/share/apache-tomcat/webapps/examples/jsp/images/execute.gif
/usr/share/apache-tomcat/webapps/examples/jsp/images/return.gif
/usr/share/apache-tomcat/webapps/examples/jsp/include/foo.html
/usr/share/apache-tomcat/webapps/examples/jsp/include/foo.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/include/foo.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/include/inc.html
/usr/share/apache-tomcat/webapps/examples/jsp/include/include.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/include/include.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/index.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/Functions.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/ValuesBean.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/ValuesTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/basic-arithmetic.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/basic-arithmetic.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/basic-arithmetic.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/basic-comparisons.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/basic-comparisons.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/basic-comparisons.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/composite.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/composite.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/composite.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/functions.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/functions.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/functions.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/implicit-objects.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/implicit-objects.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/el/implicit-objects.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/FooBean.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/HelloWorldSimpleTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/ShuffleSimpleTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/TileSimpleTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/jspattribute.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/jspattribute.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/jspattribute.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/shuffle.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/shuffle.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspattribute/shuffle.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/basic.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/basic.jspx
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/basic.jspx.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/svgexample.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/textRotate.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/textRotate.jpg
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/textRotate.jspx
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/jspx/textRotate.jspx.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/EchoAttributesTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/coda.jspf
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/coda.jspf.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/config.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/config.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/config.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/dynamicattrs.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/dynamicattrs.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/dynamicattrs.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/prelude.jspf
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/misc/prelude.jspf.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/BookBean.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/FindBookSimpleTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/Functions.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/HelloWorldSimpleTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/RepeatSimpleTag.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/book.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/book.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/book.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/hello.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/hello.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/hello.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/repeat.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/repeat.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/simpletag/repeat.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/displayProducts.tag.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/hello.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/hello.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/hello.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/helloWorld.tag.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/panel.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/panel.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/panel.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/panel.tag.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/products.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/products.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsp2/tagfiles/products.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsptoserv/ServletToJsp.java.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsptoserv/hello.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsptoserv/hello.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsptoserv/jsptoservlet.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/jsptoserv/jsptoservlet.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/jsptoserv/jts.html
/usr/share/apache-tomcat/webapps/examples/jsp/num/numguess.html
/usr/share/apache-tomcat/webapps/examples/jsp/num/numguess.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/num/numguess.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/plugin/applet/Clock2.class
/usr/share/apache-tomcat/webapps/examples/jsp/plugin/applet/Clock2.java
/usr/share/apache-tomcat/webapps/examples/jsp/plugin/plugin.html
/usr/share/apache-tomcat/webapps/examples/jsp/plugin/plugin.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/plugin/plugin.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/security/protected/error.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/security/protected/error.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/security/protected/index.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/security/protected/index.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/security/protected/login.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/security/protected/login.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/sessions/DummyCart.html
/usr/share/apache-tomcat/webapps/examples/jsp/sessions/carts.html
/usr/share/apache-tomcat/webapps/examples/jsp/sessions/carts.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/sessions/carts.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/sessions/crt.html
/usr/share/apache-tomcat/webapps/examples/jsp/simpletag/foo.html
/usr/share/apache-tomcat/webapps/examples/jsp/simpletag/foo.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/simpletag/foo.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/snp/snoop.html
/usr/share/apache-tomcat/webapps/examples/jsp/snp/snoop.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/snp/snoop.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/choose.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/choose.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/choose.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/foreach.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/foreach.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/foreach.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/howto.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/if.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/if.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/if.jsp.html
/usr/share/apache-tomcat/webapps/examples/jsp/tagplugin/notes.html
/usr/share/apache-tomcat/webapps/examples/jsp/xml/xml.html
/usr/share/apache-tomcat/webapps/examples/jsp/xml/xml.jsp
/usr/share/apache-tomcat/webapps/examples/jsp/xml/xml.jsp.html
/usr/share/apache-tomcat/webapps/examples/servlets/cookies.html
/usr/share/apache-tomcat/webapps/examples/servlets/helloworld.html
/usr/share/apache-tomcat/webapps/examples/servlets/images/code.gif
/usr/share/apache-tomcat/webapps/examples/servlets/images/execute.gif
/usr/share/apache-tomcat/webapps/examples/servlets/images/return.gif
/usr/share/apache-tomcat/webapps/examples/servlets/index.html
/usr/share/apache-tomcat/webapps/examples/servlets/nonblocking/bytecounter.html
/usr/share/apache-tomcat/webapps/examples/servlets/reqheaders.html
/usr/share/apache-tomcat/webapps/examples/servlets/reqinfo.html
/usr/share/apache-tomcat/webapps/examples/servlets/reqparams.html
/usr/share/apache-tomcat/webapps/examples/servlets/sessions.html
/usr/share/apache-tomcat/webapps/examples/websocket/chat.xhtml
/usr/share/apache-tomcat/webapps/examples/websocket/drawboard.xhtml
/usr/share/apache-tomcat/webapps/examples/websocket/echo.xhtml
/usr/share/apache-tomcat/webapps/examples/websocket/index.xhtml
/usr/share/apache-tomcat/webapps/examples/websocket/snake.xhtml
/usr/share/apache-tomcat/webapps/host-manager/META-INF/context.xml
/usr/share/apache-tomcat/webapps/host-manager/WEB-INF/jsp/401.jsp
/usr/share/apache-tomcat/webapps/host-manager/WEB-INF/jsp/403.jsp
/usr/share/apache-tomcat/webapps/host-manager/WEB-INF/jsp/404.jsp
/usr/share/apache-tomcat/webapps/host-manager/WEB-INF/web.xml
/usr/share/apache-tomcat/webapps/host-manager/images/asf-logo.svg
/usr/share/apache-tomcat/webapps/host-manager/images/tomcat.gif
/usr/share/apache-tomcat/webapps/host-manager/index.jsp
/usr/share/apache-tomcat/webapps/host-manager/manager.xml
/usr/share/apache-tomcat/webapps/manager/META-INF/context.xml
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/401.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/403.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/404.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/connectorCerts.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/connectorCiphers.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/connectorTrustedCerts.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/sessionDetail.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/jsp/sessionsList.jsp
/usr/share/apache-tomcat/webapps/manager/WEB-INF/web.xml
/usr/share/apache-tomcat/webapps/manager/images/asf-logo.svg
/usr/share/apache-tomcat/webapps/manager/images/tomcat.gif
/usr/share/apache-tomcat/webapps/manager/index.jsp
/usr/share/apache-tomcat/webapps/manager/status.xsd
/usr/share/apache-tomcat/webapps/manager/xform.xsl
/usr/share/defaults/tomcat/conf/catalina.policy
/usr/share/defaults/tomcat/conf/catalina.properties
/usr/share/defaults/tomcat/conf/context.xml
/usr/share/defaults/tomcat/conf/jaspic-providers.xml
/usr/share/defaults/tomcat/conf/jaspic-providers.xsd
/usr/share/defaults/tomcat/conf/logging.properties
/usr/share/defaults/tomcat/conf/server.xml
/usr/share/defaults/tomcat/conf/tomcat-users.xml
/usr/share/defaults/tomcat/conf/tomcat-users.xsd
/usr/share/defaults/tomcat/conf/web.xml

%files doc
%defattr(0644,root,root,0755)
%doc /usr/share/doc/apache\-tomcat/*
